DATALOADER:
  ROOT: data/custom
  CSV: train.json
  BATCH_SIZE: 1
  SHUFFLE: True
  NUM_WORKERS: 4
MODEL:
  PRETRAINED: False
  NUM_CLASSES: 2 #Background + UpperBody
OPTIMIZER:
  LEARNING_RATE: 0.00001
LR_SCHEDULER:
  MILESTONES:
  - 3
  - 4
  GAMMA: 0.1
TRAINER:
  NUM_OF_EPOCHS: 50
  SCORE_THRESHOLD: 0.6
  NMS_THRESHOLD: 0.3